const products = [
  {
    id: 1,
    name: "Tennis Shoes",
    price: "890.00",
    description:
      "Best selection for your game. Breathable material, high grip soles.",
    category: "Tennis",
    options: ["Size 7", "Size 8", "Size 9", "Size 10"],
    image: "/images/tennisshoes.jpeg",
  },
  {
    id: 2,
    name: "Soccer Shirt",
    price: "845.00",
    description: "Selection of your favourite soccer team shirts.",
    category: "Soccer",
    options: ["Manchester United", "Newcastle", "Liverpool", "Orlando Pirates"],
    image: "/images/teamshirts.jpeg",
  },
  {
    id: 3,
    name: "Cricket Bat",
    price: "980.00",
    description:
      "Assorted high-quality Cricket bats. All your favourite brands available",
    category: "Cricket",
    options: ["GM", "Match", "Kookaburra", "Grey Nichols"],
    image: "/images/cricketbats.jpeg",
  },
  {
    id: 4,
    name: "Cricket Helmet",
    price: "620.00",
    description:
      "Strong and durable helmets for all ages. Designed for comfort and visibility.",
    category: "Cricket",
    options: ["Youth", "Adult"],
    image: "/images/crickethelmet.jpeg",
  },
  {
    id: 5,
    name: "Rugby Ball",
    price: "430.00",
    description:
      "Durable rugby balls for competitive matches, maximum grip and aerodynamics. ",
    category: "Rugby",
    options: ["Gilbert", "Canterbury", "Medalist"],
    image: "/images/rugbyball.jpeg",
  },
  {
    id: 6,
    name: "Rugby Jersey",
    price: "850.00",
    description: "Your favourite Rugby Team jerseys available.",
    category: "Rugby",
    options: ["South Africa", "England", "New Zealnd", "Australia"],
    image: "/images/rugbyjerseys.jpeg",
  },
  {
    id: 7,
    name: "Tennis Racket",
    price: "1120.00",
    description:
      "Lightweight tennis rackets, perfect for any skill level. Top brands in store.",
    category: "Tennis",
    options: ["Babolat", "Dunlop", "Prince", "Wilson"],
    image: "/images/tennisrackets.jpeg",
  },
  {
    id: 8,
    name: "Tennis Balls",
    price: "110.00",
    description:
      "Pack of 3 high-quality tennis balls for every court type. Unmatched quality",
    category: "Tennis",
    options: ["Dunlop", "Wilson", "slazenger"],
    image: "/images/tennisballs.jpeg",
  },
  {
    id: 9,
    name: "Cricket Pads",
    price: "770.00",
    description: "Safe and comfortable pads, top brands available.",
    category: "Cricket",
    options: ["Kookaburra", "GM", "Grey Nichols"],
    image: "/images/cricketpads.jpeg",
  },
  {
    id: 10,
    name: "Rugby Boots",
    price: "970.00",
    description: "Lightweight, quality rugby boots available in various sizes.",
    category: "Rugby",
    options: ["Size 7", "Size 8", "Size 9", "Size 10"],
    image: "/images/rugbyboots.jpeg",
  },
  {
    id: 11,
    name: "Soccer Ball",
    price: "525.00",
    description: "Premium quality soccer ball for all conditions.",
    category: "Soccer",
    options: ["Size 4", "Size 5"],
    image: "/images/soccerball.jpg",
  },
  {
    id: 12,
    name: "Wrist Bands",
    price: "170.00",
    description: "Designed for comfort and maximum absorption.",
    category: "Tennis",
    options: ["Wilson", "Nike", "Dunlop"],
    image: "/images/tenniswristbands.jpeg",
  },
  {
    id: 13,
    name: "Shin Guards",
    price: "350.00",
    description:
      "Lightweight, stylish and easy to use. Available in various sizes.",
    category: "Soccer",
    options: ["Youth", "Adult"],
    image: "/images/shinguards.jpg",
  },
  {
    id: 14,
    name: "Cricket Ball",
    price: "200.00",
    description:
      "Perfect for school, club and training. Available in all colours and weights.",
    category: "Cricket",
    options: ["Dukes", "SG", "Kookaburra"],
    image: "/images/cricketball.jpeg",
  },
  {
    id: 15,
    name: "Rugby Socks",
    price: "330.00",
    description:
      "Perfect balance of support and flexibility. Made with high quality cottons",
    category: "Rugby",
    options: ["Adidas", "Nike", "Lotto"],
    image: "/images/rugbysocks.jpeg",
  },
  {
    id: 16,
    name: "Soccer Boots",
    price: "930.00",
    description:
      "Soccer boots for a range of surfaces. Premium brands in store",
    category: "Soccer",
    options: ["Adidas", "Nike", "Predator", "Mizuno"],
    image: "/images/soccerboots.jpg",
  },
];

export default products;
