const products = [
  {
    id: 1,
    name: "Soccer Ball",
    price: "25.00",
    description: "Premium quality soccer ball for all weather conditions.",
    category: "Soccer",
    options: ["Size 4", "Size 5"],
    image: "/images/soccer_ball.jpg",
  },
  {
    id: 2,
    name: "Soccer Jersey",
    price: "45.00",
    description: "Lightweight and comfortable jersey for soccer players.",
    category: "Soccer",
    options: ["Small", "Medium", "Large", "X-Large"],
    image: "/images/soccer_jersey.jpg",
  },
  {
    id: 3,
    name: "Cricket Bat",
    price: "80.00",
    description: "Professional-grade cricket bat for power hitters.",
    category: "Cricket",
    options: ["Short Handle", "Long Handle"],
    image: "/images/cricket_bat.jpg",
  },
  {
    id: 4,
    name: "Cricket Gloves",
    price: "20.00",
    description: "Ergonomic cricket gloves for enhanced grip and comfort.",
    category: "Cricket",
    options: ["Youth", "Adult"],
    image: "/images/cricket_gloves.jpg",
  },
  {
    id: 5,
    name: "Rugby Ball",
    price: "30.00",
    description: "Durable rugby ball for competitive matches.",
    category: "Rugby",
    options: ["Size 4", "Size 5"],
    image: "/images/rugby_ball.jpg",
  },
  {
    id: 6,
    name: "Rugby Jersey",
    price: "50.00",
    description: "High-performance rugby jersey for intense matches.",
    category: "Rugby",
    options: ["Small", "Medium", "Large", "X-Large"],
    image: "/images/rugby_jersey.jpg",
  },
  {
    id: 7,
    name: "Tennis Racket",
    price: "120.00",
    description: "Lightweight tennis racket for precision and power.",
    category: "Tennis",
    options: ["Standard", "Oversized"],
    image: "/images/tennis_racket.jpg",
  },
  {
    id: 8,
    name: "Tennis Balls",
    price: "10.00",
    description: "Pack of 3 high-quality tennis balls for every court type.",
    category: "Tennis",
    options: ["Pack of 3", "Pack of 6"],
    image: "/images/tennis_balls.jpg",
  },
];

export default products;
